### ISSUE TITLE
hitting with "invalid syntax" 

### ISSUE THREAD

**Issue by ChaitanyaHaritash** [huntergregal/mimipenguin#4]
hey nice project .. but i am hitting with an invalid syntax 

Tried on : 
Linux Mint 17.2 Cinnamon 

thanks :) 

![screenshot from 2017-04-03 14 27 55](https://cloud.githubusercontent.com/assets/16261173/24602353/0eaf2bbe-187a-11e7-893e-801e632b4865.png)

**Comment by huntergregal** [comment]
Thanks!

I dealt with this a bit during dev and thought i fixed it but clearly not.

Out of curiosity what version of python are you using? Also I think this issue is the back slash in your password. I will write a patch for this in a few :) Thanks for bringing this up.

**Comment by huntergregal** [comment]
This should now be fixed, please test it if you can.
Closing

**Comment by ChaitanyaHaritash** [comment]
hey! now i can see clear text passwords but still getting invalid syntax in crypt module in python .. tho i uses python 2.7 .. have you made this code compatible with python 3.x?  
![screenshot from 2017-04-04 06 27 50](https://cloud.githubusercontent.com/assets/16261173/24637606/1020b73e-1900-11e7-9320-9933292a7ebf.png)
